apiVersion: v1
kind: Service
metadata:
  name: mpfrontend-service
spec:
  selector:
    app: mpfrontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpfrontend-deployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: mpfrontend
  template:
    metadata:
      labels:
        app: mpfrontend
    spec:
      containers:
      - name: mpfrontend
        image: bisho11/miniprojetfrontend:latest
        ports:
          - containerPort: 80
            name: frontend-port