apiVersion: v1
kind: Service
metadata:
  name: mpfrontend-service
spec:
  selector:
    app: mpfrontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpfrontend-deployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: mpfrontend
  template:
    metadata:
      labels:
        app: mpfrontend
    spec:
      containers:
      - name: mpfrontend
        image: bisho11/miniprojetfrontend:prod
        ports:
          - containerPort: 80
            name: frontend-port
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          failureThreshold: 5 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 30
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600
  disruptionBudget:
    maxUnavailable: 1