apiVersion: v1
kind: Service
metadata:
  name: mpbackend-service
spec:
  selector:
    app: mpbackend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpbackend-deployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: mpbackend
  template:
    metadata:
      labels:
        app: mpbackend
    spec:
      containers:
      - name: mpbackend
        image: bisho11/miniprojetbackend:env2
        ports:
          - containerPort: 8080
            name: backend-port
        env:
        - name: DATABASE_URL
          valueFrom: 
            configMapKeyRef: 
              name: mpdatabase-configmap
              key : url
        - name: DATABASE_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mpdatabase-secrets
              key : password
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          failureThreshold: 5 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 30
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600
  disruptionBudget:
    maxUnavailable: 1